sudo: required
services:
    - docker

before_install:
    - docker build -t osuarez/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run osuarez/react-test npm test -- --coverage


after_success:
    - docker build -t osuarez/multi-client ./client
    - docker build -t osuarez/multi-nginx ./nginx
    - docker build -t osuarez/multi-server ./server
    - docker build -t osuarez/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push osuarez/multi-client
    - docker push osuarez/multi-nginx
    - docker push osuarez/multi-server
    - docker push osuarez/multi-worker
    
